---
- hosts: localhost
  connection: local
  vars:
    user: mrnie
  tasks:
  - name: Delete resource group
    azure_rm_resourcegroup:
      name: "webserver_{{ user }}"
      location: northeurope
      state: absent
      force_delete_nonempty: yes